from adjacency_matrix import adj_mat

def build_matricies():
    MA = adj_mat(7)
    MA.add_edge(1, 2)
    MA.add_edge(1, 4)
    MA.add_edge(2, 5)
    MA.add_edge(2, 7)
    MA.add_edge(3, 4)
    MA.add_edge(3, 6)
    MA.add_edge(3, 7)
    MA.add_edge(4, 5)
    MA.add_edge(5, 6)
    MA.add_edge(5, 7)

    MB = adj_mat(7)
    MB.add_edge(1, 4)
    MB.add_edge(1, 5)
    MB.add_edge(2, 3)
    MB.add_edge(2, 4)
    MB.add_edge(3, 4)
    MB.add_edge(4, 7)
    MB.add_edge(5, 6)
    MB.add_edge(6, 7)

    MC = adj_mat(7, directed=True)
    MC.add_edge(1, 2)
    MC.add_edge(1, 4)
    MC.add_edge(1, 5)
    MC.add_edge(2, 3)
    MC.add_edge(2, 4)
    MC.add_edge(2, 7)
    MC.add_edge(3, 4)
    MC.add_edge(4, 6)
    MC.add_edge(4, 7)
    MC.add_edge(5, 4)
    MC.add_edge(6, 5)
    MC.add_edge(7, 6)

    MD = adj_mat(7, directed=True)
    MD.add_edge(1, 2)
    MD.add_edge(1, 4)
    MD.add_edge(1, 5)
    MD.add_edge(2, 3)
    MD.add_edge(3, 7)
    MD.add_edge(4, 2)
    MD.add_edge(4, 3)
    MD.add_edge(4, 6)
    MD.add_edge(4, 7)
    MD.add_edge(5, 4)
    MD.add_edge(6, 7)
    
    return (MA.get_mat(), MB.get_mat(), MC.get_mat(), MD.get_mat())


if __name__ == "__main__":
    ma, mb, mc, md = build_matricies()
    starting_node = 1

    # print("ADJACENCY MATRIX DEPTH FIRST")
    # print(f'{"*" * 20}')
    # adj_mat.depth_first(ma, starting_node)
    # print(f'{"-" * 20}')
    # adj_mat.depth_first(mb, starting_node)
    # print(f'{"-" * 20}')
    # adj_mat.depth_first(mc, starting_node)
    # print(f'{"-" * 20}')
    # adj_mat.depth_first(md, starting_node)
    # print(f'{"-" * 20}')


    # print("ADJACENCY MATRIX BREADTH FIRST")
    # print(f'{"*" * 20}')
    # adj_mat.breadth_first(ma, starting_node)
    # print(f'{"-" * 20}')
    # adj_mat.breadth_first(mb, starting_node)
    # print(f'{"-" * 20}')
    # adj_mat.breadth_first(mc, starting_node)
    # print(f'{"-" * 20}')
    # adj_mat.breadth_first(md, starting_node)
    # print(f'{"-" * 20}')